export enum StatutCandidature {
  APPLIQUEE = 'APPLIQUEE',
  ENTRETIEN_TELEPHONIQUE = 'ENTRETIEN_TELEPHONIQUE',
  ENTRETIEN_TECHNIQUE = 'ENTRETIEN_TECHNIQUE',
  ENTRETIEN_RH = 'ENTRETIEN_RH',
  OFFRE = 'OFFRE',
  REFUSEE = 'REFUSEE',
  SANS_REPONSE = 'SANS_REPONSE'
}
